# 1. Intercepter le trafic HTTP et le rediriger vers HTTPS
server {
    listen 80;
    listen [::]:80;
    
    server_name http://leducl.3il-rodez-projets.site; 

    return 301 https://$host$request_uri;
}

# 2. Servir l'application sur HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name http://leducl.3il-rodez-projets.site;

    ssl_certificate     /etc/nginx/ssl/ton_certificat.crt;
    ssl_certificate_key /etc/nginx/ssl/ta_cle_privee.key;



    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}